server:
  address: ${SPRING_SERVER_ADDRESS:localhost}
  servlet:
    session:
      timeout: 90m

security:
  cors:
    allowed-origins: ${SPRING_SECURITY_ALLOWED_ORIGINS:http://localhost:3000}
#    allowed-origins: ${SPRING_SECURITY_ALLOWED_ORIGINS:http://localhost:3000},https://tosspayments.com


spring:
  web:
    resources:
      static-locations: classpath:/static/

  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

logging:
  file:
    name: application.log
  level:
    org:
      springframework:
        web: DEBUG
        websocket: DEBUG

    quiz:
      exquiz_me:
        card: DEBUG

toss:
  payment:
    client_api_key: test_ck_BX7zk2yd8yOONe00xvlQVx9POLqK
    secreate_api_key: test_sk_vZnjEJeQVxzkozZRgWk98PmOoBN0
    success_url: "http://localhost:8080/api/v1/payments/toss/success"
    fail_url: "http://localhost:8080/api/v1/payments/toss/fail"
